### ISSUE TITLE
Листок 3, задачи 3-4, 6-7, 9-10

### ISSUE THREAD

**Issue by phuuda** [mkuznets/hse-ling-algorithms#49]
допускается ли в решении использование дополнительной памяти: O(1) ?

**Comment by mkuznets** [comment]
@phuuda я может неправильно понял вопрос, но любое решение требует *как минимум* `O(1)`, хотя бы просто потому что вам надо объявлять какие-нибудь переменные.

А если вопрос про то, в какое время следует уложиться, то
* 3-4 можно решить за `O(1)`
* в 6-й память потребуется только для создания нового массива из `k` элементов чтобы возвратить их из функции, в остальном, как и в Quicksort, это `O(1)`
* в 7-й — `O(n+m)` в худшем случае, где `n` и `m` — размеры исходных массивов
* В 9-10 будет достаточно уложиться в `O(n)`, где `n` — длина строки
