### ISSUE TITLE
Задача 3-08

### ISSUE THREAD

**Issue by ghost** [mkuznets/hse-ling-algorithms#83]
Добрый вечер, я мимокрокодил, но хочу уточнить, точно ли в задаче 3-08 должно хватить константной памяти?

**Comment by mkuznets** [comment]
Кажется что да, если массивы in-place отсортировать и пройтись по обоим, как в слиянии массивов из mergesort

**Comment by ghost** [comment]
о. подумаю
а у вас будет разбор задач после контеста?

**Comment by mkuznets** [comment]
Возможно =/
Пока не очень понятно со временем.

**Comment by ghost** [comment]
Спасибо за ответы,
я, кажется, понял что делать в отй задаче
